export * from "./components/employee-salary/employee-salary.component";
export * from "./components/payslip/payslip.component";
export * from './components/school-fees/school-fees.component';
export * from './components/pay/pay.component';
export * from "./components/payments/payments.component";
export * from "./components/expenses/expenses.component";
export * from "./components/invoices/invoices.component";
export * from "./components/provident-fund/provident-fund.component";
export * from "./components/taxes/taxes.component";